// Dummy seed data for the logged-in family. Swapped for Zoho / Ramp / QuickBooks later.
// "Today" in the demo is early October 2026; some checklist items are overdue on purpose
// so the nudge UI has something to show.

import type {
  Budget,
  ChecklistItem,
  Family,
  Mentor,
  MentorMeeting,
  MentorMessage,
  Pin,
  PortalEvent,
  StaffFollowUp,
  StarProgress,
  VisitInfo,
} from "./types";

export const seedFamily: Family = {
  id: "fam_1042",
  familyName: "Delgado",
  address: {
    street: "418 Maple Ridge Rd",
    city: "Chillicothe",
    state: "OH",
    zip: "45601",
  },
  parents: [
    {
      id: "par_2081",
      firstName: "Rosa",
      lastName: "Delgado",
      relationship: "Mother",
      email: "rosa.delgado@example.com",
      phone: "(740) 555-0142",
      isPrimary: true,
    },
    {
      id: "par_2082",
      firstName: "Marcus",
      lastName: "Delgado",
      relationship: "Father",
      email: "marcus.delgado@example.com",
      phone: "(740) 555-0178",
      isPrimary: false,
    },
  ],
  stars: [
    {
      id: "star_3310",
      firstName: "Sofia",
      lastName: "Delgado",
      grade: 5,
      school: "Silver Creek Elementary",
      schoolDistrict: "Ross Valley Local Schools",
      program: "Voyager",
      cohort: "2025 Cohort",
      joinedDate: "2025-06-09",
    },
  ],
};

export const seedProgress: StarProgress[] = [
  {
    starId: "star_3310",
    courses: [
      {
        id: "crs_01",
        starId: "star_3310",
        title: "Prealgebra 1",
        provider: "Art of Problem Solving",
        term: "Fall 2025",
        status: "completed",
        grade: "A",
        startDate: "2025-09-08",
        endDate: "2025-12-15",
      },
      {
        id: "crs_02",
        starId: "star_3310",
        title: "Prealgebra 2",
        provider: "Art of Problem Solving",
        term: "Spring 2026",
        status: "completed",
        grade: "A-",
        startDate: "2026-01-12",
        endDate: "2026-04-27",
      },
      {
        id: "crs_03",
        starId: "star_3310",
        title: "Introduction to Number Theory",
        provider: "Art of Problem Solving",
        term: "Fall 2026",
        status: "in-progress",
        startDate: "2026-09-08",
        endDate: "2026-12-14",
      },
      {
        id: "crs_04",
        starId: "star_3310",
        title: "Introduction to Algebra A",
        provider: "Art of Problem Solving",
        term: "Spring 2027",
        status: "enrolled",
        startDate: "2027-01-11",
        endDate: "2027-05-03",
      },
    ],
    competitions: [
      {
        id: "cmp_01",
        starId: "star_3310",
        name: "Math Kangaroo",
        date: "2026-03-19",
        level: "National",
        result: "Top 5% Nationally",
        score: "112 / 120",
      },
      {
        id: "cmp_02",
        starId: "star_3310",
        name: "MOEMS Elementary Division",
        date: "2026-02-11",
        level: "National",
        result: "Gold Pin",
        score: "23 / 25",
      },
      {
        id: "cmp_03",
        starId: "star_3310",
        name: "Southern Ohio Elementary Math Bowl",
        date: "2025-11-15",
        level: "State",
        result: "2nd Place, Individual",
      },
      {
        id: "cmp_04",
        starId: "star_3310",
        name: "Ross County Math Night",
        date: "2025-10-23",
        level: "Regional",
        result: "1st Place",
      },
    ],
    camps: [
      {
        id: "cmp_s01",
        starId: "star_3310",
        name: "Math & Robotics Day Camp",
        location: "Columbus, OH",
        startDate: "2025-07-13",
        endDate: "2025-07-19",
        status: "completed",
        notes: "First NMS-funded summer camp.",
      },
      {
        id: "cmp_s02",
        starId: "star_3310",
        name: "Math Explorers Residential Camp",
        location: "Durham, NC",
        startDate: "2026-06-21",
        endDate: "2026-07-03",
        status: "completed",
        notes: "NMS-funded summer camp · combinatorics and proof writing.",
      },
      {
        id: "cmp_s03",
        starId: "star_3310",
        name: "STEM Summer Camp 2027 (NMS-funded)",
        location: "Ann Arbor, MI",
        startDate: "2027-06-20",
        endDate: "2027-07-02",
        status: "applied",
      },
    ],
  },
];

export const seedBudget: Budget = {
  familyId: "fam_1042",
  fiscalYear: "2026–27",
  maxCents: 250_000,
  transactions: [
    {
      id: "txn_01",
      date: "2026-07-06",
      description: "Fall chess lessons (10 sessions)",
      vendor: "Queen City Chess Academy",
      category: "Clubs & Lessons",
      amountCents: 35_000,
      status: "paid",
    },
    {
      id: "txn_02",
      date: "2026-07-20",
      description: "Science center family membership",
      vendor: "Scioto Science Center",
      category: "Memberships",
      amountCents: 18_000,
      status: "paid",
    },
    {
      id: "txn_03",
      date: "2026-08-02",
      description: "Beginner telescope for Stargazer pin",
      vendor: "Orion Telescopes",
      category: "Equipment",
      amountCents: 21_999,
      status: "paid",
    },
    {
      id: "txn_04",
      date: "2026-08-12",
      description: "Math puzzle books and strategy games",
      vendor: "Bookshop.org",
      category: "Books & Games",
      amountCents: 8640,
      status: "paid",
    },
    {
      id: "txn_05",
      date: "2026-08-28",
      description: "Robotics club fall season fees",
      vendor: "Ross County 4-H Robotics",
      category: "Clubs & Lessons",
      amountCents: 27_500,
      status: "paid",
    },
    {
      id: "txn_06",
      date: "2026-09-12",
      description: "Weekend coding workshop",
      vendor: "Code Ninjas Columbus",
      category: "Workshops",
      amountCents: 12_500,
      status: "paid",
    },
    {
      id: "txn_07",
      date: "2026-09-19",
      description: "Mileage — robotics club meet-up",
      vendor: "Delgado Family",
      category: "Travel",
      amountCents: 9630,
      status: "paid",
    },
    {
      id: "txn_08",
      date: "2026-09-30",
      description: "Robotics tournament registration",
      vendor: "FIRST LEGO League Ohio",
      category: "Competitions",
      amountCents: 15_000,
      status: "pending",
    },
  ],
};

export const seedMentors: Mentor[] = [
  {
    id: "men_01",
    name: "Dr. Alicia Nguyen",
    title: "Math Mentor",
    state: "OH",
    specialty: "Number theory & competition prep",
    email: "alicia.nguyen@example.org",
    startDate: "2026-08-15",
    sessionSchedule: "Weekly with Sofia · Tuesdays, 4:30 PM · 45 min",
    starId: "star_3310",
  },
  {
    id: "men_02",
    name: "James Whitfield",
    title: "Family Advisor (Midwest)",
    state: "IN",
    specialty: "Monthly check-ins, school advocacy & gifted programs",
    email: "james.whitfield@example.org",
    startDate: "2025-06-09",
  },
  {
    id: "men_04",
    name: "Dana Ortiz",
    title: "Finance & Operations Associate",
    state: "TX",
    specialty: "Budgets, purchases & reimbursements",
    email: "dana.ortiz@example.org",
    startDate: "2024-01-08",
  },
  {
    id: "men_03",
    name: "Priya Raman",
    title: "Math Mentor",
    state: "MI",
    specialty: "Problem solving & proof writing",
    email: "priya.raman@example.org",
    startDate: "2025-06-09",
    endDate: "2026-08-14",
    starId: "star_3310",
  },
];

export const seedChecklist: ChecklistItem[] = [
  {
    id: "chk_01",
    title: "Submit 2026–27 media release form",
    shortDesc: "Lets NMS share photos of Sofia from camps and events.",
    dueDate: "2026-09-15",
    isDone: false,
    url: "https://example.org/forms/media-release",
    nudgeCount: 2,
    estMinutes: 2,
    ownerName: "Rosa Delgado",
    required: true,
    area: "family",
  },
  {
    id: "chk_02",
    title: "Upload fall report card",
    shortDesc: "A photo or scan of Sofia's most recent report card.",
    dueDate: "2026-09-26",
    isDone: false,
    url: "https://example.org/forms/report-card",
    nudgeCount: 1,
    estMinutes: 5,
    ownerName: "Rosa Delgado",
    required: true,
    area: "progress",
  },
  {
    id: "chk_03",
    title: "Schedule a fall goals call with Sofia's math mentor",
    shortDesc: "30-minute parent call to set semester goals (separate from Sofia's weekly sessions).",
    dueDate: "2026-10-10",
    isDone: false,
    nudgeCount: 0,
    estMinutes: 2,
    ownerName: "Rosa Delgado",
    mentorId: "men_01",
    required: true,
    area: "mentor",
    completesWhen: "mentor-meeting-scheduled",
  },
  {
    id: "chk_04",
    title: "Submit receipts for robotics club fees",
    shortDesc: "Needed so the purchase can be reconciled against your budget.",
    dueDate: "2026-10-15",
    isDone: false,
    url: "https://example.org/forms/receipts",
    nudgeCount: 0,
    estMinutes: 5,
    ownerName: "Marcus Delgado",
    required: true,
    area: "budget",
  },
  {
    id: "chk_05",
    title: "Complete Number Theory week 4 problem set",
    shortDesc: "Due in the AoPS classroom before Friday's session.",
    dueDate: "2026-10-09",
    isDone: false,
    url: "https://artofproblemsolving.com/class",
    nudgeCount: 0,
    estMinutes: 30,
    ownerName: "Sofia Delgado",
    mentorId: "men_01",
    required: false,
    area: "progress",
  },
  {
    id: "chk_06",
    title: "Annual family information update",
    shortDesc: "Confirm address, school, and contact details are current.",
    dueDate: "2026-08-31",
    isDone: true,
    completedDate: "2026-08-22",
    nudgeCount: 0,
    ownerName: "Rosa Delgado",
    required: true,
    area: "family",
  },
  {
    id: "chk_07",
    title: "Sign 2026–27 participation agreement",
    shortDesc: "Annual program agreement for Voyager families.",
    dueDate: "2026-08-15",
    isDone: true,
    completedDate: "2026-08-03",
    url: "https://example.org/forms/agreement",
    nudgeCount: 1,
    ownerName: "Rosa Delgado",
    required: true,
    area: "family",
  },
  {
    id: "chk_08",
    title: "Apply for NMS Summer Intensive 2027",
    shortDesc: "Early application window closes in December.",
    dueDate: "2026-12-01",
    isDone: true,
    completedDate: "2026-09-21",
    url: "https://example.org/camps/2027",
    nudgeCount: 0,
    ownerName: "Rosa Delgado",
    mentorId: "men_02",
    required: false,
    area: "progress",
  },
];

export const seedEvents: PortalEvent[] = [
  {
    id: "evt_01",
    title: "Voyager Math Club",
    description:
      "Weekly drop-in session where Stars work through challenge problems together with a mentor.",
    format: "virtual",
    start: "2026-10-07T18:00:00-04:00",
    end: "2026-10-07T19:00:00-04:00",
    location: "Zoom",
    audience: "Stars",
    signupUrl: "https://example.org/events/problem-circle",
    isRsvped: true,
  },
  {
    id: "evt_02",
    title: "Parent Info Session: Navigating Grade Acceleration",
    description:
      "How to work with your school district on subject or whole-grade acceleration, with Q&A.",
    format: "virtual",
    start: "2026-10-15T19:30:00-04:00",
    end: "2026-10-15T20:30:00-04:00",
    location: "Zoom",
    audience: "Parents",
    signupUrl: "https://example.org/events/acceleration",
    capacity: 100,
    spotsLeft: 41,
    isRsvped: false,
  },
  {
    id: "evt_03",
    title: "Midwest Welcome Weekend",
    description:
      "Our in-person October gathering: math stations, a puzzle hunt, and time with other Voyager families.",
    format: "in-person",
    start: "2026-10-24T10:00:00-04:00",
    end: "2026-10-24T15:00:00-04:00",
    location: "Ohio State University, Columbus, OH",
    audience: "Families",
    signupUrl: "https://example.org/events/ky-math-day",
    capacity: 80,
    spotsLeft: 12,
    isRsvped: true,
  },
  {
    id: "evt_04",
    title: "MOEMS Practice Contest",
    description: "A timed practice round ahead of the winter MOEMS contest.",
    format: "virtual",
    start: "2026-11-04T17:30:00-05:00",
    end: "2026-11-04T18:30:00-05:00",
    location: "Zoom",
    audience: "Stars",
    signupUrl: "https://example.org/events/moems-practice",
    isRsvped: false,
  },
  {
    id: "evt_05",
    title: "Guest Talk: The Math of Space Missions",
    description:
      "An aerospace engineer shares how orbital math gets spacecraft where they need to go.",
    format: "virtual",
    start: "2026-11-12T19:00:00-05:00",
    end: "2026-11-12T20:00:00-05:00",
    location: "Zoom",
    audience: "Families",
    signupUrl: "https://example.org/events/space-math",
    capacity: 300,
    spotsLeft: 188,
    isRsvped: false,
  },
  {
    id: "evt_06",
    title: "Winter Math Jam & Chess Tournament",
    description:
      "Quarterly virtual event: team math jam, then a friendly Stars chess tournament.",
    format: "virtual",
    start: "2026-12-05T13:00:00-05:00",
    end: "2026-12-05T15:00:00-05:00",
    location: "Zoom",
    audience: "Families",
    signupUrl: "https://example.org/events/tn-meetup",
    capacity: 60,
    spotsLeft: 27,
    isRsvped: false,
  },
];

export const seedMeetings: MentorMeeting[] = [];

export const seedMessages: MentorMessage[] = [
  {
    id: "msg_01",
    mentorId: "men_01",
    from: "mentor",
    sentAt: "2026-09-24T16:12:00-04:00",
    body: "Hi Rosa! Sofia had a great first few weeks in Number Theory — she explained modular arithmetic to the group on Tuesday. Let's find time for our fall check-in to set goals for the semester.",
  },
  {
    id: "msg_02",
    mentorId: "men_01",
    from: "family",
    sentAt: "2026-09-24T20:45:00-04:00",
    body: "Thank you! She came home so excited about it. I'll grab a time on your calendar this week.",
  },
];

export const seedFollowUps: StaffFollowUp[] = [
  {
    id: "fu_01",
    title: "Register Sofia for Introduction to Algebra A",
    shortDesc: "NMS pays course tuition directly — we'll confirm her Spring 2027 seat.",
    staffId: "men_04",
    dueDate: "2026-09-30",
    isDone: false,
  },
  {
    id: "fu_02",
    title: "Reimburse robotics club fees",
    shortDesc: "Reimbursed within 10 business days of receiving your receipts.",
    staffId: "men_04",
    dueDate: "2026-10-30",
    isDone: false,
    blockedBy: "chk_04",
  },
  {
    id: "fu_03",
    title: "Share fall semester goals for Sofia",
    shortDesc: "A short written plan after your check-in call.",
    staffId: "men_01",
    dueDate: "2026-10-20",
    isDone: false,
    blockedBy: "chk_03",
  },
  {
    id: "fu_04",
    title: "Send Ross Valley grade-acceleration guide",
    shortDesc: "District policy summary and a sample request letter.",
    staffId: "men_02",
    dueDate: "2026-10-09",
    isDone: false,
  },
  {
    id: "fu_05",
    title: "Mail Math Kangaroo certificate and pin",
    shortDesc: "Shipped to your home address.",
    staffId: "men_02",
    dueDate: "2026-09-15",
    isDone: true,
    completedDate: "2026-09-11",
  },
];

export const seedPins: Pin[] = [
  {
    id: "pin_prime",
    starId: "star_3310",
    name: "Prime Hunter",
    area: "Math",
    icon: "hash",
    description: "Find, test, and explain prime numbers like a real number theorist.",
    requirements: [
      { id: "pin_prime_r1", text: "List every prime under 100 using the Sieve of Eratosthenes", done: true, completedDate: "2025-10-02" },
      { id: "pin_prime_r2", text: "Explain why there are infinitely many primes", done: true, completedDate: "2025-10-20" },
      { id: "pin_prime_r3", text: "Find a prime with at least 6 digits", done: true, completedDate: "2025-11-03" },
    ],
    earnedDate: "2025-11-03",
    verifiedBy: "men_03",
  },
  {
    id: "pin_code",
    starId: "star_3310",
    name: "First Program",
    area: "Technology",
    icon: "code",
    description: "Write a program that makes the computer do something new.",
    requirements: [
      { id: "pin_code_r1", text: "Complete an intro coding course or tutorial", done: true, completedDate: "2026-04-10" },
      { id: "pin_code_r2", text: "Write a program that solves a math problem", done: true, completedDate: "2026-05-01" },
      { id: "pin_code_r3", text: "Show your program to your mentor", done: true, completedDate: "2026-05-08" },
    ],
    earnedDate: "2026-05-08",
    verifiedBy: "men_03",
  },
  {
    id: "pin_proof",
    starId: "star_3310",
    name: "Proof Writer",
    area: "Math",
    icon: "scroll",
    description: "Write a proof so clear that anyone can follow it.",
    requirements: [
      { id: "pin_proof_r1", text: "Write a proof by induction", done: true, completedDate: "2026-09-10" },
      { id: "pin_proof_r2", text: "Write a proof by contradiction", done: true, completedDate: "2026-09-19" },
      { id: "pin_proof_r3", text: "Revise a proof using mentor feedback", done: true, completedDate: "2026-09-26" },
    ],
    earnedDate: "2026-09-26",
    verifiedBy: "men_01",
  },
  {
    id: "pin_star",
    starId: "star_3310",
    name: "Stargazer",
    area: "Science",
    icon: "telescope",
    description: "Explore the night sky and the math that maps it.",
    requirements: [
      { id: "pin_star_r1", text: "Keep a 2-week observation log of the Moon", done: true, completedDate: "2026-09-14" },
      { id: "pin_star_r2", text: "Identify 5 constellations", done: true, completedDate: "2026-09-22" },
      { id: "pin_star_r3", text: "Calculate the Moon's distance with a simple model", done: true, completedDate: "2026-10-01" },
    ],
    earnedDate: "2026-10-01",
    verifiedBy: "men_01",
  },
  {
    id: "pin_pattern",
    starId: "star_3310",
    name: "Pattern Detective",
    area: "Math",
    icon: "sigma",
    description: "Spot the hidden pattern, then prove it always works.",
    requirements: [
      { id: "pin_pattern_r1", text: "Explore Pascal's triangle and find 3 patterns", done: true, completedDate: "2026-09-12" },
      { id: "pin_pattern_r2", text: "Write a formula for a pattern you discovered", done: true, completedDate: "2026-09-25" },
      { id: "pin_pattern_r3", text: "Present your pattern at a Problem-Solving Circle", done: false },
    ],
  },
  {
    id: "pin_bridge",
    starId: "star_3310",
    name: "Bridge Builder",
    area: "Engineering",
    icon: "construction",
    description: "Design a bridge, predict its strength, then test it.",
    requirements: [
      { id: "pin_bridge_r1", text: "Sketch a bridge design with measurements", done: true, completedDate: "2026-09-05" },
      { id: "pin_bridge_r2", text: "Build it from craft sticks or paper", done: false },
      { id: "pin_bridge_r3", text: "Test the load and compare to your prediction", done: false },
    ],
  },
  {
    id: "pin_combo",
    starId: "star_3310",
    name: "Counting Wizard",
    area: "Math",
    icon: "dices",
    description: "Count the uncountable with combinatorics.",
    requirements: [
      { id: "pin_combo_r1", text: "Learn permutations and combinations", done: false },
      { id: "pin_combo_r2", text: "Solve 10 counting problems", done: false },
      { id: "pin_combo_r3", text: "Explain the pigeonhole principle", done: false },
    ],
  },
  {
    id: "pin_lab",
    starId: "star_3310",
    name: "Lab Notebook",
    area: "Science",
    icon: "flask",
    description: "Run real experiments and record them like a scientist.",
    requirements: [
      { id: "pin_lab_r1", text: "Design an experiment with a hypothesis", done: true, completedDate: "2026-09-20" },
      { id: "pin_lab_r2", text: "Run it 3 times and record results", done: false },
      { id: "pin_lab_r3", text: "Graph your data and draw a conclusion", done: false },
    ],
  },
  {
    id: "pin_data",
    starId: "star_3310",
    name: "Data Detective",
    area: "Technology",
    icon: "chart",
    description: "Turn messy data into a story with charts.",
    requirements: [
      { id: "pin_data_r1", text: "Collect 30+ data points about something you care about", done: false },
      { id: "pin_data_r2", text: "Make 2 different charts of your data", done: false },
      { id: "pin_data_r3", text: "Present one surprising finding", done: false },
    ],
  },
  {
    id: "pin_robot",
    starId: "star_3310",
    name: "Robot Wrangler",
    area: "Engineering",
    icon: "bot",
    description: "Build and program a robot to complete a challenge.",
    requirements: [
      { id: "pin_robot_r1", text: "Assemble a robot kit or design your own", done: false },
      { id: "pin_robot_r2", text: "Program it to navigate a maze", done: false },
    ],
  },
];

// Last visit was about two weeks ago, so "since your last visit" has something to show.
export const seedVisit: VisitInfo = {
  previous: null,
  current: "2026-09-18T19:30:00-04:00",
};
